"""Second time

Revision ID: 01917e05d61c
Revises: e7515799dc9a
Create Date: 2023-06-10 10:54:29.028315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01917e05d61c'
down_revision = 'e7515799dc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['serial_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
