"""empty message

Revision ID: d5b2a9924d06
Revises: 01917e05d61c
Create Date: 2023-06-10 11:04:04.902115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5b2a9924d06'
down_revision = '01917e05d61c'
branch_labels = ('pera',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.drop_constraint('phone_serial_number_key', type_='unique')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('phone_serial_number_key', ['serial_number'])
    # ### end Alembic commands ###
